# -----------------------------------------------------------------------------
# @file state_estimator_params.yaml
# @brief Configuration file for the EstimationManager node.
# @author Wagner Dantas Garcia / Laser UAV Team
# @date September 10, 2025
#
# This file defines all parameters for the `estimation_manager` node. It
# controls the EKF behavior, the drone's physical parameters, noise gains,
# and sensor synchronization settings.
# -----------------------------------------------------------------------------
/**/**:
  ros__parameters:

    # --- General Node Parameters ---

    # Frequency (in Hz) of the main estimation loop (predict + correct).
    frequency: 100.0

    # Main reference frame for the filter's output odometry.
    frame_id: "uav1/fcu"

    # --- Thresholds for Dynamic Odometry Source Switching ---
    # If a new odometry source is further from the current state than these
    # limits, the switch will be rejected to prevent jumps in the estimate.
    odometry_switch_distance_threshold: 0.25 # Max distance in meters.
    odometry_switch_angle_threshold: 0.1 # Max angular difference in radians.
    odometry_switch_velocity_linear_threshold: 0.1 # Max linear velocity difference in m/s.
    odometry_switch_velocity_angular_threshold: 0.1 # Max angular velocity difference in rad/s.

    # Name of the odometry source to be activated on node startup.
    # Must match one of the names in the 'odometry_source_names' list.
    initial_odometry_source: "px4_api_odom"

    # List of all available odometry sources for the filter.
    odometry_source_names: ["px4_api_odom", "openvins_odom", "fast_lio_odom"]

    # Verbosity level for the EKF library's internal logs.
    # Options: "SILENT", "INFO", "DEBUG"
    ekf_verbosity: "INFO"

    # --- Drone Physical Parameters ---
    # These values are used in the EKF's dynamic model for the prediction step.
    drone_params:
      mass: 1.60 # Total drone mass in kg.
      arm_length: 0.258 # Distance from drone center to a motor in meters.
      thrust_coefficient: 1.0 # Motor thrust coefficient.
      torque_coefficient: 0.059 # Motor torque coefficient.
      
      # Inertia Matrix [Ixx, Iyy, Izz] in kg*m^2.
      inertia: [0.021667, 0.021667, 0.0425]

      # Motor positions (x, y) in the drone's body frame.
      motor_positions: [
         0.185, -0.18,  # Motor 0 (Front-Right)
        -0.185, 0.18,  # Motor 1 (Rear-Right)
         0.185,  0.18,  # Motor 2 (Rear-Left)
        -0.185,  -0.18   # Motor 3 (Front-Left)
      ]

    # --- PROCESS NOISE GAINS (PHYSICAL MODEL) ---
    # Controls how much we trust the prediction from the model.
    # > 1.0: Less trust (uncertainty grows faster).
    # < 1.0: More trust (uncertainty grows slower).
    process_noise_gains:
      position: 0.001
      orientation: 0.01
      linear_velocity: 0.01
      angular_velocity: 0.1

    # --- MEASUREMENT NOISE GAINS (SENSORS) ---
    # Controls how much we trust each sensor measurement.
    # > 1.0: Less trust (filter gives less weight to the measurement).
    # < 1.0: More trust (filter adjusts more towards the measurement).
    measurement_noise_gains:
      px4_odometry:
        position: 0.0001
        orientation: 0.001
        linear_velocity: 0.01
        angular_velocity: 0.01
      openvins:
        position: 0.0001
        orientation: 0.001
        linear_velocity: 0.01
        angular_velocity: 0.1
      fast_lio:
        position: 0.0001
        orientation: 0.001
        linear_velocity: 0.01
        angular_velocity: 0.1
      imu:
        angular_velocity: 0.1
        # Position, orientation, and linear velocity are not used directly from IMU for correction.
        position: 0.1        # Not used
        orientation: 0.1     # Not used
        linear_velocity: 0.1 # Not used
      gps:
        position: 0.1
        # Orientation and velocities are not provided by GPS.
        orientation: 0.1     # Not used
        linear_velocity: 0.1 # Not used
        angular_velocity: 0.1# Not used

    # --- Synchronization and Timeout Settings per Sensor ---

    # Tolerance (in seconds): Max time difference for a message to be considered synchronized.
    # Timeout (in seconds): Max time without receiving a message before considering the sensor offline.

    # Settings for PX4 Odometry
    px4_odom_tolerance: 0.015 # e.g., 1.5x the period of a 100Hz sensor
    px4_odom_timeout: 0.5

    # Settings for OpenVINS Odometry
    openvins_odom_tolerance: 0.0075 # e.g., 1.5x the period of a 200Hz sensor
    openvins_odom_timeout: 1.0

    # Settings for Fast-LIO Odometry
    fast_lio_odom_tolerance: 0.15 # e.g., 1.5x the period of a 10Hz sensor
    fast_lio_odom_timeout: 1.0

    # Settings for IMU
    imu_tolerance: 0.015
    imu_timeout: 0.5

    # Settings for Control Inputs
    control_tolerance: 0.015
    control_timeout: 0.5